spring.application.name=aws-bedrock-rag
spring.ai.model.embedding=bedrock-cohere

spring.ai.bedrock.cohere.embedding.enabled=true
spring.ai.bedrock.cohere.embedding.model=cohere.embed-multilingual-v3
spring.ai.bedrock.cohere.embedding.input-type=search_document

spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=1024
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.bedrock.cohere.embedding.truncate=END
